development:
  secret_key_base: eCs_J?O|0%l&1D-RW[GosX:W@2AM];
  google_client_id: 727516764491-jnin4n5pgethaohjnj8u4ujihpvt0uoo.apps.googleusercontent.com
  google_client_secret: eQjc_EQteEXgdM_bz9AUOz3W